# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4eeb2150ee6374ed36da02238f176c52ca8fb905dedd7d87bbf3af691644d141ede0190d1ef9d2a9298d07097f366352ce5f902439471b7df334ee1648281317

test:
  secret_key_base: 3617fe3d5f476e3f8bc36d098512db5f1bf54e11d5f77f2713625ef4d16f0d5bebafe9c95392ce343ba76a1d4a6624cb636425caa76c466e42dbd82fa6aa2281

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
